// Add Product Input
export const ADD_ITEM_INPUT = "ADD_ITEM_INPUT";
export const UPDATE_ITEM_INPUT = "UPDATE_ITEM_INPUT";
export const CLEAR_ITEM_INPUT = "CLEAR_ITEM_INPUT";

export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";

//auth
export const ADD_LOGIN_FORM_INPUT = "ADD_LOGIN_FORM_INPUT";
export const UPDATE_LOGIN_FORM_INPUT = "UPDATE_LOGIN_FORM_INPUT";
export const CLEAR_LOGIN_FORM_INPUT = "CLEAR_LOGIN_FORM_INPUT";
export const ADD_SIGNUP_FORM_INPUT = "ADD_SIGNUP_FORM_INPUT";
export const UPDATE_SIGNUP_FORM_INPUT = "UPDATE_SIGNUP_FORM_INPUT";
export const CLEAR_SIGNUP_FORM_INPUT = "CLEAR_SIGNUP_FORM_INPUT";

//profile
export const SET_PROFILE_INPUT = "SET_PROFILE_INPUT";
export const UPDATE_PROFILE_INPUT = "UPDATE_PROFILE_INPUT";
export const CLEAR_PROFILE_INPUT = "CLEAR_PROFILE_INPUT";
